Add french translation
rluders/oc-jwtauth-plugin pull request #52
Opened 2021-01-17 10:42 UTC by Incremental92

French translation with some english terms kept for clarity.

2021-01-17 19:05 UTC, rluders requested changes
There are some places where you are using single quotes inside the single quotes string on PHP. I don't think that it would be a good idea. How about replacing the string single quotes to use double quotes?

2021-01-17 19:05 UTC, rluders commented on lang/fr-fr/lang.php
> +            'urls' => 'Options d''URL',
I don't think that using the double `single quotes` here will work. The PHP string is already using `single quotes`, which would be better if you need to use the single quote character to the language if you replace the quotes that limit the string with double-quotes.

2021-01-17 19:06 UTC, rluders commented on lang/fr-fr/lang.php
> +            'urls' => 'Options d''URL',
For example, something like this:

```'urls' => "Options d''URL", ```

2021-01-19 21:57 UTC, Incremental92 commented
OK I will change it.

2021-01-20 14:54 UTC, Incremental92 commented
I made the correction.

2021-01-23 19:04 UTC, merged